/* Yue Sai · Maison des Heures — contenu du site.
   Les quatre moments suivent les douze heures doubles chinoises (十二时辰). */

window.YS = (function () {
  const MOMENTS = {
    chen: {
      key: 'chen', zh: '晨', fr: 'Éveil', pinyin: 'chén', hours: '5 h – 11 h', from: 5, to: 11,
      shichen: ['卯', '辰', '巳'],
      verb: "s'éveiller",
      line: 'Le matin, la peau se défend.',
      text: "La barrière cutanée se referme, le sébum remonte, la ville attend avec ses UV et ses particules. Le rituel du matin est court : nettoyer sans décaper, nourrir, protéger. Trois gestes, dix minutes, avant le premier message de la journée.",
      chrono: "La production de sébum et la fonction barrière augmentent au cours de la matinée. C'est l'heure des antioxydants et de la protection.",
      gesture: 'Nettoyer · nourrir · protéger',
      duree: '10 min',
      lieu: 'Le bain',
      products: ['mousse-matin', 'essence-eveil', 'ecran-urbain', 'gua-sha'],
      hero: 'amb_40', gallery: ['amb_ex3', 'amb_51', 'amb_35', 'mousse-matin_mousse'],
    },
    wu: {
      key: 'wu', zh: '午', fr: 'Recharge', pinyin: 'wǔ', hours: '11 h – 17 h', from: 11, to: 17,
      shichen: ['午', '未', '申'],
      verb: 'se recharger',
      line: "À midi, on ne se remaquille pas. On respire.",
      text: "Climatisation, écrans, réunions : la peau perd son eau dans l'après-midi. Le rituel de la journée tient dans un sac et dure trente secondes. Une brume, un baume pour les mains, et le visage reprend l'heure.",
      chrono: "Le sébum atteint son pic vers midi pendant que l'air climatisé assèche la surface. Hydrater sans alourdir, sans toucher au maquillage.",
      gesture: 'Brumiser · apaiser',
      duree: '30 s',
      lieu: 'La ville',
      products: ['brume-heures', 'baume-mains', 'ecran-urbain'],
      hero: 'ville_paparazzi', gallery: ['amb_38', 'baume-mains_empreintes', 'brume-heures', 'ecran-urbain_roche'],
    },
    mu: {
      key: 'mu', zh: '暮', fr: 'Dénouer', pinyin: 'mù', hours: '17 h – 23 h', from: 17, to: 23,
      shichen: ['酉', '戌', '亥'],
      verb: 'dénouer',
      line: 'Le soir, on défait la journée.',
      text: "Maquillage, pollution, tension de la mâchoire : tout ce que la journée a noué. L'huile d'armoise fond sous les doigts pendant trois minutes de massage. Puis on choisit : rester chez soi à la lueur d'une bougie, ou sortir avec un rouge.",
      chrono: "En fin de journée, la perméabilité de la peau augmente. Un démaquillage doux et un massage préparent l'absorption des soins de nuit.",
      gesture: 'Masser · démaquiller · sortir',
      duree: '3 min',
      lieu: 'Le bar, le restaurant',
      products: ['huile-denouer', 'rouge-1992', 'bougie-lieux', 'encens-heures'],
      hero: 'amb_44', gallery: ['amb_33', 'amb_43', 'amb_46', 'amb_ex2'],
    },
    ye: {
      key: 'ye', zh: '夜', fr: 'Réparer', pinyin: 'yè', hours: '23 h – 5 h', from: 23, to: 5,
      shichen: ['子', '丑', '寅'],
      verb: 'réparer',
      line: "La nuit, la peau travaille. On la laisse faire.",
      text: "Entre minuit et quatre heures, le renouvellement cellulaire atteint son maximum. Le rituel de nuit est le plus lent : une essence réchauffée entre les paumes, une crème dans un pot de porcelaine que l'on garde à vie, et le sommeil.",
      chrono: "Le renouvellement cellulaire culmine la nuit, pendant que la perte en eau augmente. Réparer, nourrir, fermer.",
      gesture: 'Presser · nourrir · dormir',
      duree: '5 min',
      lieu: "L'hôtel",
      products: ['essence-nuit', 'creme-porcelaine', 'essence-or'],
      hero: 'creme-porcelaine_modele', gallery: ['amb_41', 'lieux_plateau', 'essence-or_nuit', 'amb_48'],
    },
  };
  const ORDER = ['chen', 'wu', 'mu', 'ye'];

  // 十二时辰 : heure de début, animal, méridien de la tradition (子午流注)
  const SHICHEN = [
    { zh: '子', start: 23, animal: 'Rat', organe: 'vésicule biliaire', m: 'ye' },
    { zh: '丑', start: 1, animal: 'Buffle', organe: 'foie', m: 'ye' },
    { zh: '寅', start: 3, animal: 'Tigre', organe: 'poumon', m: 'ye' },
    { zh: '卯', start: 5, animal: 'Lièvre', organe: 'gros intestin', m: 'chen' },
    { zh: '辰', start: 7, animal: 'Dragon', organe: 'estomac', m: 'chen' },
    { zh: '巳', start: 9, animal: 'Serpent', organe: 'rate', m: 'chen' },
    { zh: '午', start: 11, animal: 'Cheval', organe: 'cœur', m: 'wu' },
    { zh: '未', start: 13, animal: 'Chèvre', organe: 'intestin grêle', m: 'wu' },
    { zh: '申', start: 15, animal: 'Singe', organe: 'vessie', m: 'wu' },
    { zh: '酉', start: 17, animal: 'Coq', organe: 'rein', m: 'mu' },
    { zh: '戌', start: 19, animal: 'Chien', organe: 'péricarde', m: 'mu' },
    { zh: '亥', start: 21, animal: 'Cochon', organe: 'triple réchauffeur', m: 'mu' },
  ];

  // 二十四节气 : date de début approximative (mois, jour)
  const TERMS = [
    ['小寒', 'Petit froid', 1, 5], ['大寒', 'Grand froid', 1, 20], ['立春', 'Début du printemps', 2, 4],
    ['雨水', 'Eaux de pluie', 2, 19], ['惊蛰', 'Réveil des insectes', 3, 5], ['春分', 'Équinoxe de printemps', 3, 20],
    ['清明', 'Clarté pure', 4, 5], ['谷雨', 'Pluie des grains', 4, 20], ['立夏', "Début de l'été", 5, 5],
    ['小满', 'Petite plénitude', 5, 21], ['芒种', 'Grain en épi', 6, 5], ['夏至', "Solstice d'été", 6, 21],
    ['小暑', 'Petite chaleur', 7, 7], ['大暑', 'Grande chaleur', 7, 22], ['立秋', "Début de l'automne", 8, 7],
    ['处暑', 'Fin de la chaleur', 8, 23], ['白露', 'Rosée blanche', 9, 7], ['秋分', "Équinoxe d'automne", 9, 23],
    ['寒露', 'Rosée froide', 10, 8], ['霜降', 'Descente du givre', 10, 23], ['立冬', "Début de l'hiver", 11, 7],
    ['小雪', 'Petite neige', 11, 22], ['大雪', 'Grande neige', 12, 7], ['冬至', "Solstice d'hiver", 12, 21],
  ];

  const P = [
    {
      slug: 'mousse-matin', name: 'Mousse du Matin', zh: '晨露洁面慕斯', m: 'chen', price: 24, vol: '150 ml',
      tag: 'Eau de riz fermentée',
      desc: "Une mousse dense à l'eau de riz fermentée, le plus ancien geste de beauté chinois. Elle nettoie sans tirer la peau et la laisse prête à recevoir l'essence.",
      options: [['Flacon 150 ml', 24, 'verre ambré, pompe mousseuse'], ['Recharge 150 ml', 17, '−30 %, on garde le flacon']],
      imgs: ['mousse-matin_mousse', 'amb_ex3', 'amb_40'],
      ritual: ['Une noisette entre les paumes mouillées.', 'Masser trente secondes, du centre du visage vers l’extérieur.', 'Rincer à l’eau tiède, sécher en tamponnant.'],
      formula: 'Eau de riz fermentée 20 % · acides aminés de coco · glycérine végétale · pH 5,5.',
      matiere: 'Verre ambré, pompe mousseuse, étiquette en papier de riz.',
      freq: { win: [6, 9], how: 'Chaque matin', dose: 'Une noisette', dure: '150 ml ≈ 3 mois' },
      sens: ['Odeur de riz tiède et de thé vert', 'Mousse serrée, rinçage net'],
      stats: [['pH 5,5', 'celui de la peau'], ['30 s', 'le temps du geste'], ['0', 'sulfate']],
      pair: ['essence-eveil', 'ecran-urbain', 'gua-sha'],
    },
    {
      slug: 'essence-eveil', name: 'Essence Éveil', zh: '人参晨萃精华', m: 'chen', price: 46, vol: '30 ml',
      tag: 'Ginseng de Changbai · vitamine C',
      desc: "Ginseng de sous-bois des monts Changbai et vitamine C stabilisée. Le matin, la peau se défend : cette essence prépare sa barrière avant la ville.",
      options: [['Flacon 30 ml', 46, 'verre ambré, pipette, étiquette papier'], ['Recharge 30 ml', 32, '−30 %']],
      imgs: ['essence-eveil_racine', 'essence-eveil_goutte', 'amb_38'],
      ritual: ['Trois gouttes après la Mousse du Matin.', 'Presser, ne pas frotter.', "Finir par l'Écran Urbain avant de sortir."],
      formula: 'Ginseng 5 % · vitamine C stabilisée 3 % · acide hyaluronique de bas poids moléculaire.',
      matiere: "Verre ambré, pipette de verre, étiquette de papier imprimée à l'encre, sceau 羽西.",
      freq: { win: [6, 10], how: 'Chaque matin', dose: '3 gouttes', dure: '30 ml ≈ 3 mois' },
      sens: ['Racine fraîche, écorce', 'Fluide, absorbé en dix secondes'],
      stats: [['+31 %', 'éclat mesuré à 28 jours*'], ['6 ans', "l'âge minimum des racines"], ['2', 'gestes le matin, pas dix']],
      pair: ['mousse-matin', 'ecran-urbain', 'coffret-7'],
    },
    {
      slug: 'ecran-urbain', name: 'Écran Urbain SPF 50', zh: '城市防护乳', m: 'chen', price: 25, vol: '40 ml',
      tag: 'SPF 50 · PA++++',
      desc: "Filtres larges, bouclier anti-pollution, fini invisible sous le maquillage. Pensé pour le métro, la climatisation et les journées d'écran.",
      options: [['Tube 40 ml', 25, 'aluminium souple'], ['Format nomade 15 ml', 18, 'pour le sac']],
      imgs: ['ecran-urbain_ombre', 'ecran-urbain_roche', 'ecran-urbain_sepia'],
      ritual: ['Deux doigts de produit, visage et cou.', 'Dernier geste avant de sortir.', 'Renouveler à midi si l’on déjeune dehors.'],
      formula: "Filtres UVA-UVB nouvelle génération · extrait de thé vert · niacinamide 2 %.",
      matiere: "Tube d'aluminium souple, bouchon à vis, impression directe.",
      freq: { win: [7, 11], how: 'Chaque matin, et à midi dehors', dose: 'Deux doigts', dure: '40 ml ≈ 6 semaines' },
      sens: ['Sans parfum', 'Fini nu, ni blanc ni gras'],
      stats: [['SPF 50', 'UVA-UVB, testé in vivo*'], ['PA++++', 'la norme asiatique la plus haute'], ['0', 'film blanc']],
      pair: ['essence-eveil', 'brume-heures', 'coffret-7'],
    },
    {
      slug: 'gua-sha', name: 'Gua Sha', zh: '东海水晶刮痧板', m: 'chen', price: 38, vol: '1 pièce',
      tag: 'Quartz doré de Donghai',
      desc: "Une minute au réveil, le long de la mâchoire, pour dégonfler le visage. Quartz doré taillé à Donghai, la capitale chinoise du cristal. Chaque pierre a ses propres inclusions.",
      options: [['Pierre + étui de lin', 38, "certificat d'origine"]],
      imgs: ['amb_35', 'amb_34'],
      ritual: ['Garder la pierre au frais.', 'Du centre du visage vers les oreilles, sans appuyer.', 'Trois passages par zone, toujours vers le haut.'],
      formula: 'Quartz naturel, poli à la main. Aucune formule : un outil.',
      matiere: "Quartz doré de Donghai, étui de lin écru, sceau 羽西 gravé sur la tranche.",
      freq: { win: [6, 8], how: 'Chaque matin', dose: '1 minute', dure: 'Se garde à vie' },
      sens: ['Froid en main', 'Glisse sur quelques gouttes d’essence'],
      stats: [['1 min', 'le geste du matin'], ['4 °C', 'la température idéale'], ['1', 'pierre unique']],
      pair: ['essence-eveil', 'essence-nuit', 'mousse-matin'],
    },
    {
      slug: 'brume-heures', name: 'Brume des Heures', zh: '桂花时光喷雾', m: 'wu', price: 21, vol: '50 ml',
      tag: 'Osmanthus de Guilin',
      desc: "Osmanthus de Guilin, la ville natale de Madame Yue-Sai Kan, dont le nom signifie « forêt d'osmanthus ». Trente secondes, sans se remaquiller.",
      options: [['Flacon 50 ml', 21, 'verre et aluminium brossé'], ['Format nomade 15 ml', 14, 'pour le sac']],
      imgs: ['brume-heures', 'amb_51', 'ville_paparazzi'],
      ritual: ['À vingt centimètres du visage, yeux fermés.', 'Tapoter du bout des doigts.', 'Reprendre sa journée.'],
      formula: "Eau florale d'osmanthus 40 % · glycérine végétale · panthénol.",
      matiere: "Verre, capot d'aluminium brossé, graduation des douze heures sérigraphiée.",
      freq: { win: [11, 17], how: 'À midi, et quand on veut', dose: '4 pressions', dure: '50 ml ≈ 6 semaines' },
      sens: ['Osmanthus, abricot sec', 'Brume très fine, invisible sur le maquillage'],
      stats: [['30 s', 'le temps du geste'], ['+24 %', 'hydratation immédiate*'], ['0', 'effet collant']],
      pair: ['baume-mains', 'ecran-urbain', 'essence-eveil'],
    },
    {
      slug: 'baume-mains', name: 'Baume des Mains', zh: '山茶护手霜', m: 'wu', price: 19, vol: '30 ml',
      tag: 'Huile de camélia',
      desc: "L'huile de camélia, celle que les femmes du Sud de la Chine gardaient pour leurs cheveux et leurs mains. Le tube d'aluminium se froisse et garde la trace de vos doigts.",
      options: [['Tube 30 ml', 19, 'aluminium froissable']],
      imgs: ['baume-mains_empreintes', 'amb_38'],
      ritual: ['Une noisette au creux de la paume.', 'Masser les phalanges une à une.', 'Finir par le pouce, dans la paume opposée.'],
      formula: 'Huile de camélia 12 % · beurre de karité · allantoïne.',
      matiere: "Tube d'aluminium souple, sans surbouchon.",
      freq: { win: [12, 17], how: 'Aussi souvent que nécessaire', dose: 'Une noisette', dure: '30 ml ≈ 1 mois' },
      sens: ['Camélia, thé blanc', 'Pénètre sans laisser de trace sur l’écran'],
      stats: [['2 min', 'avant de retoucher un clavier'], ['12 %', "d'huile de camélia"], ['1', 'poche suffit']],
      pair: ['brume-heures', 'ecran-urbain', 'huile-denouer'],
    },
    {
      slug: 'huile-denouer', name: 'Huile Dénouer', zh: '艾草卸妆油', m: 'mu', price: 27, vol: '150 ml',
      tag: 'Armoise de Qichun',
      desc: "L'armoise de Qichun, celle de la moxibustion. L'huile fond le maquillage et la journée en trois minutes de massage, puis s'émulsionne à l'eau tiède.",
      options: [['Flacon 150 ml', 27, 'verre ambré, pompe'], ['Recharge 150 ml', 19, '−30 %']],
      imgs: ['huile-denouer_eau-hd', 'huile-denouer_eau', 'gamme_pierres', 'amb_44'],
      ritual: ['Sur peau sèche, deux pressions dans les mains.', 'Massage circulaire trois minutes, des tempes vers la mâchoire.', "Émulsionner à l'eau tiède, sécher sans frotter."],
      formula: "Huiles de carthame et de sésame · extrait d'armoise 3 % · vitamine E.",
      matiere: "Verre ambré sérigraphié, pompe noire, étui au grain de papier xuan.",
      freq: { win: [19, 22], how: 'Chaque soir', dose: '2 pressions', dure: '150 ml ≈ 2 mois' },
      sens: ['Armoise, herbe sèche, un peu de fumée', 'Huile fondante qui devient lait'],
      stats: [['3 min', 'le temps du rituel'], ['98 %', 'de démaquillage, yeux compris*'], ['0', 'parfum de synthèse']],
      pair: ['essence-nuit', 'rouge-1992', 'bougie-lieux'],
    },
    {
      slug: 'rouge-1992', name: 'Rouge 1992', zh: '一九九二唇膏', m: 'mu', price: 29, vol: '3,5 g',
      tag: 'Quatre rouges chinois',
      desc: "La réédition du rouge fondateur, lancé par Madame Yue-Sai Kan en 1992. Quatre teintes tirées de la palette chinoise, du rouge des jupes de mariée au fard des dames Tang. Il fond à la chaleur des lèvres.",
      options: [['Étui + rouge', 29, 'mine gravée YUE SAI'], ['Recharge seule', 16, "on garde l'étui"]],
      shades: [['石榴红', 'Grenade', '#8E1F24'], ['覆盆子', 'Framboise', '#A0243F'], ['朱砂', 'Cinabre', '#B3382A'], ['胭脂', 'Yanzhi', '#9A4650']],
      imgs: ['rouge-1992_flamme', 'rouge-1992_campagne', 'matiere_grenade', 'matiere_framboise', 'amb_43'],
      ritual: ['Au doigt pour un voile, au pinceau pour un trait net.', 'Se porte seul, sans autre maquillage.', 'Un baiser sur un mouchoir pour fixer.'],
      formula: 'Cires végétales · pigments minéraux · huile de camélia.',
      matiere: 'Mine gravée, étui laqué, sceau 羽西 gravé sous le culot.',
      freq: { win: [18, 23], how: 'Pour sortir', dose: 'Deux passages', dure: '3,5 g ≈ 300 poses' },
      sens: ['Framboise, violette', 'Crème puis mat en une minute'],
      stats: [['1992', "l'année du rouge fondateur"], ['8 h', 'de tenue*'], ['4', 'rouges chinois']],
      pair: ['huile-denouer', 'coffret-rituels', 'brume-heures'],
    },
    {
      slug: 'bougie-lieux', name: 'Bougie des Lieux', zh: '艾檀香氛蜡烛', m: 'mu', price: 58, vol: '220 g',
      tag: 'Armoise & santal',
      desc: "L'odeur de nos Lieux du Temps : celle du hall, de la chambre et du bar de nos hôtels partenaires. On la retrouve chez soi, et un soir on la reconnaît ailleurs.",
      options: [['Bougie 220 g', 58, 'céramique côtelée, 50 heures'], ['Recharge de cire', 34, 'on garde la céramique']],
      imgs: ['bougie-lieux', 'amb_46', 'amb_ex2'],
      ritual: ['Allumer une heure, pas plus.', 'Couper la mèche à cinq millimètres.', 'Éteindre avec le couvercle, jamais en soufflant.'],
      formula: 'Cire de colza et de coco · mèche de coton · armoise, santal, thé fumé.',
      matiere: 'Céramique côtelée émaillée à Jingdezhen, gravée YUE SAI.',
      freq: { win: [19, 23], how: 'Le soir', dose: 'Une heure', dure: '220 g ≈ 50 heures' },
      sens: ['Armoise, santal, thé fumé', 'Flamme basse, sans suie'],
      stats: [['50 h', 'de combustion'], ['1', 'odeur, partout la même'], ['à vie', 'la céramique se recharge']],
      pair: ['encens-heures', 'huile-denouer', 'coffret-rituels'],
    },
    {
      slug: 'encens-heures', name: 'Encens des Quatre Heures', zh: '四时线香', m: 'mu', price: 68, vol: '4 × 20 bâtonnets',
      tag: 'Une odeur par moment',
      desc: "Quatre boîtes, une par moment : thé vert au matin, osmanthus à midi, armoise et santal le soir, bois d'agar la nuit. Un bâtonnet brûle vingt minutes, le temps d'un rituel.",
      options: [['Coffret 4 boîtes', 68, 'avec porte-encens en céladon'], ['Une boîte', 19, '20 bâtonnets']],
      imgs: ['encens-heures', 'amb_48', 'amb_46'],
      ritual: ['Allumer, attendre la flamme, souffler.', 'Poser sur le porte-encens en céladon.', 'Vingt minutes : la durée d’un rituel.'],
      formula: "晨 thé vert · 午 osmanthus · 暮 armoise & santal · 夜 bois d'agar & jujube. Poudres végétales, liant de bois de Machilus.",
      matiere: 'Coffret de papier gaufré, quatre boîtes illustrées, porte-encens en céladon.',
      freq: { win: [17, 23], how: 'Un bâtonnet par rituel', dose: '20 minutes', dure: '80 bâtonnets' },
      sens: ['Bois, herbes, résine', 'Fumée fine et droite'],
      stats: [['20 min', 'par bâtonnet'], ['4', 'odeurs, 4 moments'], ['80', 'bâtonnets']],
      pair: ['bougie-lieux', 'coffret-rituels', 'essence-nuit'],
    },
    {
      slug: 'essence-nuit', name: 'Essence Nuit Lingzhi', zh: '灵芝夜萃精华', m: 'ye', price: 61, vol: '30 ml',
      tag: 'Lingzhi · jujube · niacinamide',
      desc: "Le soir, la barrière cutanée devient plus perméable et le renouvellement cellulaire s'accélère : c'est l'heure où une essence travaille le mieux. Lingzhi cultivé sur bûches, jujube du Xinjiang, niacinamide.",
      options: [['Flacon 30 ml', 61, 'verre, pipette'], ['Recharge 30 ml', 43, '−30 %, le flacon se garde'], ["Coffret d'essai", 12, '7 jours, remboursé']],
      imgs: ['essence-nuit_main', 'gamme_pierres', 'amb_41'],
      ritual: ["Après l'Huile Dénouer, trois gouttes réchauffées deux secondes entre les paumes.", 'Presser, ne pas frotter, des tempes vers le centre.', 'Finir par la Crème Porcelaine.'],
      formula: 'Lingzhi 4 % · jujube 2 % · niacinamide 5 % · squalane végétal.',
      matiere: 'Verre, pipette, impression directe à l’encre brune.',
      freq: { win: [22, 24], how: 'Chaque soir', dose: '3 gouttes', dure: '30 ml ≈ 3 mois' },
      sens: ['Bois humide, datte', 'Huile-sérum, fond en quelques secondes'],
      stats: [['+22 %', 'barrière cutanée à 28 jours*'], ['60', 'volontaires, panels asiatique et européen*'], ['92 %', 'dorment mieux avec le rituel complet*']],
      pair: ['creme-porcelaine', 'huile-denouer', 'essence-or'],
    },
    {
      slug: 'creme-porcelaine', name: 'Crème Porcelaine', zh: '红枣瓷肌面霜', m: 'ye', price: 89, vol: '50 ml',
      tag: 'Jujube du Xinjiang · céramides',
      desc: "Une crème riche au jujube du Xinjiang et aux céramides, pour la nuit. Le pot en porcelaine de Jingdezhen se garde à vie ; la recharge se glisse dedans.",
      options: [['Pot en porcelaine 50 ml', 89, 'Jingdezhen, couvercle sculpté'], ['Recharge 50 ml', 62, 'se glisse dans le pot']],
      imgs: ['creme-porcelaine_modele', 'porcelaine_tour', 'creme-porcelaine_trio'],
      ritual: ["Une noisette, réchauffée au bout des doigts.", 'Envelopper le visage, puis le cou.', 'Refermer le pot : le couvercle se tourne jusqu’au déclic.'],
      formula: 'Jujube 3 % · céramides NP, AP, EOP · beurre de karité · peptides.',
      matiere: 'Porcelaine de Jingdezhen émaillée, couvercle sculpté, recharge en capsule.',
      freq: { win: [22, 24], how: 'Chaque soir, dernier geste', dose: 'Une noisette', dure: '50 ml ≈ 2 mois' },
      sens: ['Datte, lait tiède', 'Riche, fond en baume'],
      stats: [['à vie', 'le pot se garde'], ['3', 'céramides'], ['−30 %', 'la recharge']],
      pair: ['essence-nuit', 'essence-or', 'encens-heures'],
    },
    {
      slug: 'essence-or', name: 'Essence Or Cordyceps', zh: '虫草金萃精华', m: 'ye', price: 160, vol: '30 ml',
      tag: 'Cordyceps fermenté', badge: 'Prestige',
      desc: "Cordyceps de fermentation, jamais sauvage : l'espèce est menacée et se vend jusqu'à 35 000 $ le kilo. La biotechnologie donne la même molécule sans toucher au plateau tibétain.",
      options: [['Flacon calebasse 30 ml', 160, 'bouchon gravé à votre prénom'], ['Recharge 30 ml', 111, 'le flacon se garde à vie']],
      imgs: ['essence-or_blanc', 'essence-or_nuit'],
      ritual: ["Trois gouttes, le soir, après l'Essence Nuit.", 'Réchauffer entre les paumes.', 'Presser du bas vers le haut.'],
      formula: 'Cordyceps fermenté 6 % · proxylane · peptides.',
      matiere: "Flacon calebasse 葫芦 dans une cloche de verre soufflé. Dans la médecine chinoise, la gourde est le signe du remède : 悬壶济世, suspendre la gourde pour soigner le monde.",
      freq: { win: [22, 24], how: 'Chaque soir', dose: '3 gouttes', dure: '30 ml ≈ 3 mois' },
      sens: ['Miel, ambre', "Or liquide, pénètre en une minute"],
      stats: [['+29 %', 'fermeté à 56 jours*'], ['0', 'cordyceps sauvage prélevé'], ['à vie', 'le flacon se recharge']],
      pair: ['essence-nuit', 'creme-porcelaine', 'coffret-rituels'],
    },
    {
      slug: 'coffret-7', name: 'Coffret 7 Jours', zh: '七日体验礼盒', m: 'chen', mark: '初', price: 12, vol: '28 unidoses',
      tag: "L'essai, remboursé", badge: 'Essai',
      desc: "Vingt-huit unidoses, quatre par jour, une par moment. Le prix est rendu en bon d'achat sur la première routine complète.",
      options: [['Coffret 7 jours', 12, 'remboursé sur la première routine']],
      imgs: ['coffret-7_sachets', 'lieux_enveloppe'],
      ritual: ['Chaque jour, quatre sachets : 晨 午 暮 夜.', 'Un sachet par moment, à l’heure indiquée.', 'Au septième jour, le Carnet des Heures dit quelle routine garder.'],
      formula: '7 doses Mousse du Matin · 7 Essence Éveil · 7 Brume des Heures · 7 Essence Nuit.',
      matiere: "Sachets céladon, boîte en carton gaufré, livrée dans l'enveloppe Yue Sai.",
      freq: { win: [5, 29], how: 'Sept jours, quatre moments', dose: 'Un sachet', dure: '7 jours' },
      sens: ['Toute la journée en une boîte'],
      stats: [['28', 'unidoses'], ['100 %', 'du prix rendu'], ['7', 'jours pour juger']],
      pair: ['essence-eveil', 'essence-nuit', 'brume-heures'],
    },
    {
      slug: 'coffret-rituels', name: 'Coffret Les Quatre Rituels', zh: '四时之礼礼盒', m: 'mu', mark: '全', price: 248, vol: '4 soins',
      tag: 'La journée entière', badge: 'Cadeau',
      desc: "Les quatre rituels dans un coffret doré gaufré de racines de ginseng. À offrir pour la fête de la Mi-Automne, le Nouvel An, ou à soi-même.",
      options: [['Coffret doré', 248, 'gravure du prénom offerte'], ['Coffret découverte', 96, '4 formats voyage']],
      imgs: ['coffret-rituels_or', 'gamme_pierres', 'lieux_enveloppe'],
      ritual: ['Essence Éveil 30 ml', 'Brume des Heures 50 ml', 'Huile Dénouer 150 ml', 'Essence Nuit Lingzhi 30 ml'],
      formula: 'Le coffret contient quatre soins pleine taille et le Carnet des Heures personnalisé.',
      matiere: "Coffret doré gaufré, anse de cuir ; étui kraft et étiquette de papier xuan pour la version découverte.",
      freq: { win: [5, 29], how: 'Un rituel par moment', dose: '4 soins', dure: '≈ 3 mois' },
      sens: ['Toute la journée'],
      stats: [['4', 'rituels'], ['−18 %', 'face aux soins séparés'], ['1', 'prénom gravé']],
      pair: ['essence-or', 'encens-heures', 'coffret-7'],
    },
  ];

  const LIEUX = [
    { t: '07:10', lieu: 'Le bain', img: 'amb_51', m: 'chen', text: "Dans les salles de bain de nos hôtels, la Mousse du Matin et le même flacon ambré qu'à la maison." },
    { t: '12:40', lieu: 'La rue', img: 'ville_paparazzi', m: 'wu', text: 'La Brume des Heures tient dans un sac. Trente secondes entre deux rendez-vous.' },
    { t: '19:30', lieu: 'Le restaurant', img: 'amb_ex2', m: 'mu', text: "Sous la cloche, une fumée d'armoise. Les bols en céladon ont la même cuvette du pouce que nos flacons." },
    { t: '21:00', lieu: 'Le bar', img: 'amb_46', m: 'mu', text: "Une infusion sans alcool servie en céladon. L'air sent l'armoise et le santal, comme la Bougie des Lieux." },
    { t: '22:15', lieu: 'La chambre', img: 'lieux_cloche', m: 'mu', text: 'Sous la cloche du room service, une carte Yue Sai : le rituel du soir vous attend dans la salle de bain.' },
    { t: '22:40', lieu: 'La couverture', img: 'lieux_plateau', m: 'ye', text: "Au moment de la couverture, le plateau d'argent : l'Essence Nuit, la Crème Porcelaine, la brume d'oreiller." },
    { t: 'Le lendemain', lieu: 'La lettre', img: 'lieux_enveloppe', m: 'chen', text: "Une enveloppe au nom de la cliente, scellée au cinabre : le rituel de la chambre, à retrouver chez soi." },
  ];

  const MAISON = [
    { img: 'amb_6', t: 'Devant la porte', text: "Deux arches de laque, aucune enseigne. À droite, une plaque de cinabre grande comme une main : 羽西. C'est tout ce qui est écrit." },
    { img: 'amb_10', t: 'Le seuil', text: 'Vingt-quatre niches, une par terme solaire. Seule celle du jour est allumée, et le rituel de la quinzaine change avec elle.' },
    { img: 'amb_8', t: 'Le salon des Heures', text: "La lumière suit l'heure réelle : blanche à sept heures, ambrée à dix-huit, presque bleue à minuit." },
    { img: 'amb_11', t: 'Le siège du diagnostic', text: 'Quinze minutes assise, un thé, des questions sur le sommeil et la saison. Le Carnet des Heures est scellé devant vous.' },
    { img: 'amb_48', t: 'Les cabines', text: "Au fond, les cabines de soin : pierre, eau, lumière rasante. Le soin de la saison dure quarante minutes." },
  ];

  const MATIERES = [
    { zh: '人参', fr: 'Ginseng', lieu: 'Monts Changbai, Jilin', img: 'essence-eveil_racine', text: 'Racines de sous-bois de six ans minimum. Dans l’Essence Éveil.', p: 'essence-eveil' },
    { zh: '石榴', fr: 'Grenade', lieu: 'Lintong, Shaanxi', img: 'matiere_grenade', text: "Le rouge des jupes de mariée, 石榴红. La première teinte du Rouge 1992.", p: 'rouge-1992' },
    { zh: '覆盆子', fr: 'Framboise', lieu: 'Heilongjiang', img: 'matiere_framboise', text: 'Un rouge qui a du jus. La deuxième teinte du Rouge 1992.', p: 'rouge-1992' },
    { zh: '艾草', fr: 'Armoise', lieu: 'Qichun, Hubei', img: 'huile-denouer_eau-hd', text: "L'herbe de la moxibustion, récoltée au cinquième mois lunaire. Dans l'Huile Dénouer et la Bougie des Lieux.", p: 'huile-denouer' },
    { zh: '灵芝', fr: 'Lingzhi', lieu: 'Longquan, Zhejiang', img: 'essence-nuit_main', text: 'Cultivé sur bûches, jamais cueilli. Dans l’Essence Nuit.', p: 'essence-nuit' },
    { zh: '虫草', fr: 'Cordyceps', lieu: 'Fermentation, Shanghai', img: 'essence-or_blanc', text: "Fermenté en laboratoire : le cordyceps sauvage est menacé. Dans l'Essence Or.", p: 'essence-or' },
    { zh: '红枣', fr: 'Jujube', lieu: 'Hotan, Xinjiang', img: 'creme-porcelaine_modele', text: 'La datte rouge du désert. Dans la Crème Porcelaine et l’Essence Nuit.', p: 'creme-porcelaine' },
    { zh: '桂花', fr: 'Osmanthus', lieu: 'Guilin, Guangxi', img: 'amb_51', text: 'La ville natale de Madame Yue-Sai Kan. Dans la Brume des Heures.', p: 'brume-heures' },
    { zh: '米水', fr: 'Eau de riz', lieu: 'Wuchang, Heilongjiang', img: 'mousse-matin_mousse', text: 'Le plus ancien geste de beauté chinois, fermenté. Dans la Mousse du Matin.', p: 'mousse-matin' },
    { zh: '山茶', fr: 'Camélia', lieu: 'Jiangxi', img: 'baume-mains_empreintes', text: "L'huile des cheveux et des mains du Sud. Dans le Baume des Mains.", p: 'baume-mains' },
  ];

  const STATUTS = [
    { zh: '坯', fr: "L'Ébauche", cond: "Dès l'inscription", text: 'Diagnostic, Carnet des Heures, sceau numérique, recharges à −30 %, un rituel à chaque terme solaire.' },
    { zh: '釉', fr: "L'Émail", cond: 'Quatre saisons suivies ou 400 € par an', text: 'Prénom gravé, un soin en cabine par saison, avant-premières de 48 heures.' },
    { zh: '瓷', fr: 'La Porcelaine', cond: 'Douze saisons ou 1 300 € par an', text: 'Sceau de pierre gravé à la main, édition réservée, reconnue dans toutes les Maisons du monde.' },
  ];

  return { MOMENTS, ORDER, SHICHEN, TERMS, P, LIEUX, MAISON, MATIERES, STATUTS };
})();
